# Generated by Django 4.0.3 on 2022-04-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
