# Generated by Django 4.0.3 on 2022-04-01 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/parking_spaces'),
            preserve_default=False,
        ),
    ]
