# Generated by Django 4.0.3 on 2022-04-01 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_parkingspace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
