# Generated by Django 4.0.3 on 2022-04-05 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_parkingspace_latitude_parkingspace_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_favourite', to=settings.AUTH_USER_MODEL)),
                ('parkingSpace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.parkingspace')),
            ],
        ),
    ]
