# Generated by Django 4.0.3 on 2022-04-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='key',
            new_name='parkingSpace',
        ),
    ]
