# Generated by Django 4.0.3 on 2022-04-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_parkingspace_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='image',
            field=models.CharField(max_length=10000000),
        ),
    ]
