# Generated by Django 4.0.3 on 2022-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_key_image_parkingspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
