# Generated by Django 4.0.3 on 2022-04-01 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_parkingspace_alter_customuser_is_staff_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='notes',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='consumer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_transaction', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='users.vehicle'),
        ),
    ]
