# Generated by Django 4.0.3 on 2022-04-11 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_parkingspace_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='n_ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='notes',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='size',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('4WD/SUV', '4WD/SUV'), ('Van', 'Van')], default='Hatchback', max_length=50),
        ),
    ]
