# Generated by Django 4.0.3 on 2022-04-08 02:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_parkingspace_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_array', to='users.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='n_ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
