# Generated by Django 4.0.3 on 2022-04-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_parkingspace_images_alter_image_parkingspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='n_ratings',
            field=models.IntegerField(null=True),
        ),
    ]
