# Generated by Django 4.0.3 on 2022-04-08 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_parkingspace_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='parkingSpace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parkingspace'),
        ),
    ]
