# Generated by Django 4.0.3 on 2022-04-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_image_parkingspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_data',
            field=models.CharField(default='sadasdas', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='parkingSpace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.parkingspace'),
        ),
    ]
