# Generated by Django 4.0.3 on 2022-04-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_image_image_data_alter_image_parkingspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_data',
            field=models.CharField(max_length=10000000),
        ),
    ]
