# Generated by Django 4.0.3 on 2022-04-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_image_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_data',
            field=models.CharField(max_length=1000000),
        ),
    ]
