# Generated by Django 4.0.3 on 2022-04-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_parkingspace_avg_rating_parkingspace_endtime_and_more'),
        ('users', '0016_alter_parkingspace_notes'),
    ]

    operations = [
    ]
