# Generated by Django 4.0.3 on 2022-04-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20220411_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
