# Generated by Django 4.0.3 on 2022-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_parkingspace_latesttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='latestTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='n_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
