# Generated by Django 4.0.4 on 2022-04-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_transaction_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='carRego',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
