# Generated by Django 4.0.4 on 2022-04-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_parkingspace_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
